# Tools of the trade

Before you start engaging in analysis development work within your agency, you'll need to make sure you have the right tools to get the job done.

There are two software tools every analyst should utilize: a scripting-based data analysis platform and a version control system.

## Data analysis software

The most commonly used data analysis software is Microsoft Excel. While nearly every analyst cuts their teeth crafting spreadsheets and pivot tables in this popular software, it's not an ideal platform for professional analysis developers. Excel's cell-based structure obscures the formulae that drive analysis work, making it hard for others (and often yourself) to understand what's actually going on "under the hood."

Scripting-based data analysis languages are the cure for the common spreadsheet. They make the entire analysis process transparent by explicitly stating what actions will happen and the order in which they will be executed. 

I use and heartily recommend using R as your main platform for data analysis. It is free, open-source, and has a vibrant community of developers and practitioners working to improve the language.

