# Communication is key

Building a team of analysis developers starts with a foundation of honest, humble, and frequent communication. Most analysis developers in education agencies start their careers in isolation, left to their own devices to work with the data for a particular program area or set of schools. Breaking out of that isolation to collaborate with others is difficult, but it all starts with developing strong and supportive systems of communication.

## Meet regularly

It may sound obvious, but the first step to establishing good communication as a team of analysis developers is to start meeting and talking on a regular basis. As busy as things can get in our agencies, it is worth carving out an hour of your week to get together and talk about your current projects, challenges you're facing, and successes you're realizing. If an hour seems like too much, start with a half hour, but start this habit as soon as you can.

Meeting regularly with your team of analysis developers has several benefits. It provides your teammates with the opportunity to step back from their day-to-day work and share their perspective. If one person is struggling with a particular part of a project, another teammate may have tackled a similar challenge earlier in the year and be able to share how they were able to overcome it. These serendipitous moments of collaboration and informal professional development are much more likely to occur if you establish a forum for these conversations to occur. 

More importantly, meeting regularly helps to establish stronger informal relationships between team members. Not every item on the agenda needs to be strictly work-related, you can also take time to share part of your non-office life. This is a form of team-building that is often overlooked, but it shouldn't be ignored. Even seemingly-mundane small-talk about what you have planned for the weekend can help build trust and rapport between teammates, making the challenge of forming a high-functioning team much less daunting. 

## Establish norms

As you start to meet regularly with your team, you will also want to take the time to establish and model healthy norms to support open and honest communication. Sharing your work can be a nerve-racking proposition, exponentially so if you're trying a new approach or learning a new software language. Setting expectations on the front-end of those conversations will reduce that tension and lead to more productive feedback. 

To start, make it clear that any feedback on an analysis project is strictly about the *process* and not about *the person*. Hilary Parker covers this topic in a talk she gave at the 2017 rstudio::conf(), [Opinionated Analysis Development](https://www.rstudio.com/resources/videos/opinionated-analysis-development/). She discusses the "blameless postmortem" process used during her time at Etsy, in which any errors were discussed by evaluating the *process* that led to the error, not the person responsible. Mistakes will happen in our work - an approach to resolving them that focuses on improving process over assigning blame to a person will ultimately lead to more productive and less emotional conversations. 

These conversations about the process of data analysis should be grounded in a sense of humility. While some may be more comfortable and confident in their expertise, nobody has the perfect answer to every problem. As we become experts, it's important to remember how it felt to be a novice. Any feedback we provide to others should always be done in a spirit that recognizes we tackle difficult problems and are all learning to get better with each analysis we craft. 

It is also important that while we provide feedback on processes with a sense of humility, it must also be delivered as honestly as possible. Pointing out errors in a particular analytic approach or offer more optimal workflow is good - that's how we learn and grow. But we must always take caution to make sure that this honest feedback is always focused on the *process* and not the *person*. 
